name: spotify_clone
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.5
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.1
  firebase_sign_in: ^0.0.16
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  go_router: ^14.2.3
  hydrated_bloc: ^9.1.5
  intl: ^0.19.0
  just_audio: ^0.9.39
  just_audio_background: ^0.0.1-beta.13
  path_provider: ^2.1.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/vectors/
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.ttf
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 600
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Regular.ttf
          weight: 400
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 300
