name: spotify_clone
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  cloud_firestore: ^5.6.12
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^6.0.0
  flutter_svg: ^2.0.14
  get_it: ^8.0.3
  go_router: ^14.6.2
  google_sign_in: ^6.2.2
  hydrated_bloc: ^9.1.5
  intl: ^0.19.0
  just_audio: ^0.9.42
  just_audio_background: ^0.0.1-beta.14
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/fonts/
    - assets/images/
    - assets/vectors/
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.ttf
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 600
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Regular.ttf
          weight: 400
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 300